# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_list_swig', [dirname(__file__)])
        except ImportError:
            import _list_swig
            return _list_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_list_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _list_swig = swig_import_helper()
    del swig_import_helper
else:
    import _list_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class IntList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntList, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _list_swig.IntList_data_set
    __swig_getmethods__["data"] = _list_swig.IntList_data_get
    if _newclass:data = _swig_property(_list_swig.IntList_data_get, _list_swig.IntList_data_set)
    __swig_setmethods__["max_items"] = _list_swig.IntList_max_items_set
    __swig_getmethods__["max_items"] = _list_swig.IntList_max_items_get
    if _newclass:max_items = _swig_property(_list_swig.IntList_max_items_get, _list_swig.IntList_max_items_set)
    __swig_setmethods__["n_items"] = _list_swig.IntList_n_items_set
    __swig_getmethods__["n_items"] = _list_swig.IntList_n_items_get
    if _newclass:n_items = _swig_property(_list_swig.IntList_n_items_get, _list_swig.IntList_n_items_set)
    def __init__(self, *args): 
        this = _list_swig.new_IntList(*args)
        try: self.this.append(this)
        except: self.this = this
    def append(self, *args): return _list_swig.IntList_append(self, *args)
    def get(self, *args): return _list_swig.IntList_get(self, *args)
    __swig_destroy__ = _list_swig.delete_IntList
    __del__ = lambda self : None;
IntList_swigregister = _list_swig.IntList_swigregister
IntList_swigregister(IntList)

class FloatList(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FloatList, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FloatList, name)
    __repr__ = _swig_repr
    __swig_setmethods__["data"] = _list_swig.FloatList_data_set
    __swig_getmethods__["data"] = _list_swig.FloatList_data_get
    if _newclass:data = _swig_property(_list_swig.FloatList_data_get, _list_swig.FloatList_data_set)
    __swig_setmethods__["max_items"] = _list_swig.FloatList_max_items_set
    __swig_getmethods__["max_items"] = _list_swig.FloatList_max_items_get
    if _newclass:max_items = _swig_property(_list_swig.FloatList_max_items_get, _list_swig.FloatList_max_items_set)
    __swig_setmethods__["n_items"] = _list_swig.FloatList_n_items_set
    __swig_getmethods__["n_items"] = _list_swig.FloatList_n_items_get
    if _newclass:n_items = _swig_property(_list_swig.FloatList_n_items_get, _list_swig.FloatList_n_items_set)
    def __init__(self, *args): 
        this = _list_swig.new_FloatList(*args)
        try: self.this.append(this)
        except: self.this = this
    def append(self, *args): return _list_swig.FloatList_append(self, *args)
    def get(self, *args): return _list_swig.FloatList_get(self, *args)
    __swig_destroy__ = _list_swig.delete_FloatList
    __del__ = lambda self : None;
FloatList_swigregister = _list_swig.FloatList_swigregister
FloatList_swigregister(FloatList)

# This file is compatible with both classic and new-style classes.


